export const COUNTRY_INFO = {
  'Japan': {
    code: 'JP', currency: 'JPY', flag: '🇯🇵',
    capital: 'Tokyo', timezone: 'Asia/Tokyo',
    lat: 35.6762, lng: 139.6503,
    plug: { type: 'Type A', voltage: '100V', note: 'Korean plugs need a pig-nose adapter. 220V Korean devices need a transformer.' },
    visa: { required: false, note: 'Visa-free for 90 days (tourism)' },
    sim: 'Buy at airport or convenience stores. SoftBank, au, or Docomo SIMs recommended.',
    emergency: { police: '110', fire: '119', ambulance: '119' },
    payment: 'Mostly cash. Cards accepted at convenience stores and tourist spots. Exchange JPY in advance.',
    water: 'Tap water is drinkable.',
    tips: ['Buy a transit pass (Suica/Icoca) in advance', 'Few public trash cans — carry yours', 'Free water at restaurants', 'Be quiet at shrines'],
    mustPack: ['Passport + spare photo', 'JPY cash', 'Plug adapter', 'Umbrella (frequent rain)', 'Comfortable walking shoes', 'Face mask'],
    weather: { spring: 'Cherry blossom season Mar-Apr, 15-20°C', summer: 'Jul-Aug hot and humid, 30°C+', fall: 'Autumn colors Oct-Nov', winter: 'Snow Dec-Feb, Tokyo has light snow' },
  },
  'Thailand': {
    code: 'TH', currency: 'THB', flag: '🇹🇭',
    capital: 'Bangkok', timezone: 'Asia/Bangkok',
    lat: 13.7563, lng: 100.5018,
    plug: { type: 'Type A/B/C', voltage: '220V', note: 'Most Korean plugs fit. Adapter often unnecessary.' },
    visa: { required: false, note: 'Visa-free for 30 days (tourism)' },
    sim: 'Buy TrueMove or AIS SIM at airport. ~KRW 20,000 for 7-day unlimited.',
    emergency: { police: '191', fire: '199', ambulance: '1669' },
    payment: 'Mostly cash (baht). Cards accepted at tourist spots. Watch ATM fees.',
    water: 'Tap water not drinkable. Buy bottled water.',
    tips: ['Cover legs/shoulders at temples', 'Check tuk-tuk/taxi meters', 'Grab app is handy', 'Stay hydrated in the heat'],
    mustPack: ['Passport', 'THB cash', 'Strong sunscreen', 'Shorts/t-shirts', 'Stomach medicine', 'Mosquito repellent', 'Long pants (for temples)'],
    weather: { spring: 'End of dry season Mar-Apr, 35°C+ very hot', summer: 'Rainy season May-Oct, frequent showers', fall: 'End of rains Oct-Nov', winter: 'Dry season Nov-Feb, best time to visit' },
  },
  'France': {
    code: 'FR', currency: 'EUR', flag: '🇫🇷',
    capital: 'Paris', timezone: 'Europe/Paris',
    lat: 48.8566, lng: 2.3522,
    plug: { type: 'Type C/E', voltage: '230V', note: 'Different from Korea. Type C adapter required.' },
    visa: { required: false, note: 'Schengen visa-free 90 days' },
    sim: 'Airport or Orange/SFR stores. eSIM available.',
    emergency: { police: '17', fire: '18', ambulance: '15', eu: '112' },
    payment: 'Cards widely accepted. Small amounts in cash. Exchange some EUR in advance.',
    water: 'Tap water is drinkable.',
    tips: ['Watch for pickpockets (metro, tourist spots)', 'Tipping is customary (5-10% at restaurants)', 'Many shops closed Sundays', 'Free museum entry first Sunday of the month'],
    mustPack: ['Passport', 'EUR cash', 'Type C adapter', 'Comfortable shoes', 'Light jacket (variable weather)', 'Small anti-theft bag'],
    weather: { spring: 'Mild Apr-Jun, 10-20°C', summer: 'Warm Jul-Aug, 20-30°C', fall: 'Chilly Sep-Nov, rainy', winter: 'Cold Dec-Feb, 0-10°C' },
  },
  'Italy': {
    code: 'IT', currency: 'EUR', flag: '🇮🇹',
    capital: 'Rome', timezone: 'Europe/Rome',
    lat: 41.9028, lng: 12.4964,
    plug: { type: 'Type C/F/L', voltage: '230V', note: 'Multi-country adapter recommended' },
    visa: { required: false, note: 'Schengen visa-free 90 days' },
    sim: 'TIM, Vodafone, WindTre. eSIM recommended.',
    emergency: { police: '112', fire: '115', ambulance: '118' },
    payment: 'Cards widely accepted. Keep small bills for cafes and taxis.',
    water: 'Tap water is drinkable. Fountains (nasoni) are free.',
    tips: ['Cover shoulders and knees at churches', 'Watch pickpockets at Termini and popular sites', 'Coffee is cheaper standing at the bar', 'Siesta 13:00-16:00 — many shops close'],
    mustPack: ['Passport', 'EUR cash', 'Plug adapter', 'Modest clothing for churches', 'Comfortable shoes (cobblestones)', 'Refillable water bottle'],
    weather: { spring: 'Pleasant Apr-Jun, 15-25°C', summer: 'Hot Jul-Aug, 30°C+', fall: 'Cool Sep-Nov, ideal for travel', winter: 'Mild in the south, cold in the north' },
  },
  'Vietnam': {
    code: 'VN', currency: 'VND', flag: '🇻🇳',
    capital: 'Hanoi', timezone: 'Asia/Ho_Chi_Minh',
    lat: 21.0285, lng: 105.8542,
    plug: { type: 'Type A/C', voltage: '220V', note: 'Korean plugs usually fit' },
    visa: { required: false, note: 'Visa-free for 45 days (tourism)' },
    sim: 'Viettel, Mobifone, Vinaphone at airport. Cheap.',
    emergency: { police: '113', fire: '114', ambulance: '115' },
    payment: 'Cash (VND) mostly. Cards at hotels and larger restaurants. Grab works great.',
    water: 'Tap water not drinkable. Bottled water only.',
    tips: ['Cross the street slowly and steadily', 'Negotiate prices', 'Grab app for rides/food', 'Try pho at local spots'],
    mustPack: ['Passport', 'VND/USD cash', 'Sunscreen', 'Light clothes', 'Stomach medicine', 'Mosquito repellent'],
    weather: { spring: 'Mild in north, hot in south', summer: 'Jun-Aug hot and humid', fall: 'Sep-Nov pleasant', winter: 'Cool Dec-Feb in north, warm in south' },
  },
  'Indonesia': {
    code: 'ID', currency: 'IDR', flag: '🇮🇩',
    capital: 'Jakarta', timezone: 'Asia/Jakarta',
    lat: -6.2088, lng: 106.8456,
    plug: { type: 'Type C/F', voltage: '230V', note: 'Korean 220V plugs usually fit' },
    visa: { required: false, note: 'Visa on arrival USD 35 (or apply online)' },
    sim: 'Telkomsel, XL. Buy at airport.',
    emergency: { police: '110', fire: '113', ambulance: '118' },
    payment: 'Cash (IDR) common. Cards at hotels and tourist spots. Gojek/Grab for rides.',
    water: 'Tap water not drinkable.',
    tips: ['Respect religious customs', 'Use sunscreen (equatorial sun)', 'Bali has entry fees at some temples', 'Drive on the left'],
    mustPack: ['Passport', 'IDR/USD cash', 'Strong sunscreen', 'Swimwear', 'Mosquito repellent', 'Light layers'],
    weather: { spring: 'Dry season Apr-Oct', summer: 'Hot and humid year-round, 25-32°C', fall: 'Dry continues', winter: 'Rainy season Nov-Mar' },
  },
  'Spain': {
    code: 'ES', currency: 'EUR', flag: '🇪🇸',
    capital: 'Madrid', timezone: 'Europe/Madrid',
    lat: 40.4168, lng: -3.7038,
    plug: { type: 'Type C/F', voltage: '230V', note: 'Type C adapter required' },
    visa: { required: false, note: 'Schengen visa-free 90 days' },
    sim: 'Movistar, Vodafone, Orange. eSIM works well.',
    emergency: { police: '091', fire: '080', ambulance: '061', eu: '112' },
    payment: 'Cards widely accepted. Cash for markets and small cafes.',
    water: 'Tap water generally drinkable.',
    tips: ['Siesta 14:00-17:00', 'Dinner starts late (21:00+)', 'Watch pickpockets in Barcelona', 'Tapas culture — order small and share'],
    mustPack: ['Passport', 'EUR cash', 'Plug adapter', 'Sunscreen', 'Comfortable shoes', 'Light jacket for evenings'],
    weather: { spring: 'Mild and sunny Apr-Jun', summer: 'Very hot Jul-Aug, 35°C+ inland', fall: 'Comfortable Sep-Nov', winter: 'Cool in north, mild in south' },
  },
  'USA': {
    code: 'US', currency: 'USD', flag: '🇺🇸',
    capital: 'Washington D.C.', timezone: 'America/New_York',
    lat: 38.9072, lng: -77.0369,
    plug: { type: 'Type A/B', voltage: '120V', note: 'Pig-nose adapter for Korean plugs. 220V devices need a transformer.' },
    visa: { required: true, note: 'ESTA required (90-day visa waiver)' },
    sim: 'T-Mobile, AT&T, Verizon. eSIM works well.',
    emergency: { all: '911' },
    payment: 'Cards everywhere. Tipping required (15-20% at restaurants).',
    water: 'Tap water generally drinkable.',
    tips: ['Always tip (taxi, restaurants, hotels)', 'Sales tax added at checkout', 'Large portions', 'Tip bartenders $1 per drink'],
    mustPack: ['Passport + ESTA', 'USD cash + credit card', 'Type A adapter', 'Comfortable walking shoes', 'Layers (huge climate range)'],
    weather: { spring: 'Varies widely by region', summer: 'Hot in most states Jun-Aug', fall: 'Fall foliage in Northeast', winter: 'Cold in North, mild in South' },
  },
  'Singapore': {
    code: 'SG', currency: 'SGD', flag: '🇸🇬',
    capital: 'Singapore', timezone: 'Asia/Singapore',
    lat: 1.3521, lng: 103.8198,
    plug: { type: 'Type G', voltage: '230V', note: 'Type G adapter (UK style) required' },
    visa: { required: false, note: 'Visa-free for 90 days' },
    sim: 'Singtel, StarHub, M1. Airport kiosks.',
    emergency: { police: '999', fire: '995', ambulance: '995' },
    payment: 'Cards and mobile pay everywhere. EZ-Link card for transit.',
    water: 'Tap water is drinkable.',
    tips: ['Strict laws — no gum, no littering', 'Efficient MRT covers the city', 'Hawker centers are cheap and great', 'Humidity is intense'],
    mustPack: ['Passport', 'SGD cash', 'Type G adapter', 'Light clothes', 'Umbrella', 'Sunscreen'],
    weather: { spring: 'Hot and humid year-round 25-32°C', summer: 'Same', fall: 'Same', winter: 'Same, slightly wetter Nov-Jan' },
  },
  'Hong Kong': {
    code: 'HK', currency: 'HKD', flag: '🇭🇰',
    capital: 'Hong Kong', timezone: 'Asia/Hong_Kong',
    lat: 22.3193, lng: 114.1694,
    plug: { type: 'Type G', voltage: '220V', note: 'Type G (UK) adapter required' },
    visa: { required: false, note: 'Visa-free for 90 days' },
    sim: 'csl, China Mobile HK. Airport vending machines.',
    emergency: { all: '999' },
    payment: 'Cards widely accepted. Octopus card for transit and small purchases.',
    water: 'Tap water technically drinkable but most buy bottled.',
    tips: ['Octopus card is essential', 'Dim sum in the morning', 'Star Ferry is a cheap harbor tour', 'Walk everywhere — compact city'],
    mustPack: ['Passport', 'HKD cash', 'Type G adapter', 'Comfortable shoes', 'Light layers', 'Umbrella'],
    weather: { spring: 'Mild Mar-May', summer: 'Hot and humid Jun-Aug, typhoons', fall: 'Best season Sep-Nov', winter: 'Cool Dec-Feb, 10-20°C' },
  },
  'UK': {
    code: 'GB', currency: 'GBP', flag: '🇬🇧',
    capital: 'London', timezone: 'Europe/London',
    lat: 51.5074, lng: -0.1278,
    plug: { type: 'Type G', voltage: '230V', note: 'Type G (UK) adapter required' },
    visa: { required: false, note: 'ETA required from 2024 for most nationalities' },
    sim: 'EE, Vodafone, O2, Three. eSIM common.',
    emergency: { all: '999', non_emergency: '101' },
    payment: 'Cards everywhere, contactless standard. Oyster card for London transit.',
    water: 'Tap water is drinkable.',
    tips: ['Drive on the left', 'Mind the gap on the Tube', 'Queue politely', 'Pubs close earlier than you think'],
    mustPack: ['Passport + ETA', 'GBP cash', 'Type G adapter', 'Waterproof jacket', 'Umbrella', 'Comfortable shoes'],
    weather: { spring: 'Mild but rainy Apr-Jun', summer: 'Warm Jul-Aug, 20-25°C', fall: 'Cool and wet Sep-Nov', winter: 'Cold and gray Dec-Feb' },
  },
  'Australia': {
    code: 'AU', currency: 'AUD', flag: '🇦🇺',
    capital: 'Canberra', timezone: 'Australia/Sydney',
    lat: -35.2809, lng: 149.1300,
    plug: { type: 'Type I', voltage: '230V', note: 'Type I adapter required' },
    visa: { required: true, note: 'ETA/eVisitor required online' },
    sim: 'Telstra, Optus, Vodafone. Good airport coverage.',
    emergency: { all: '000' },
    payment: 'Cards everywhere. Tap-to-pay standard.',
    water: 'Tap water is drinkable.',
    tips: ['Strong sun — SPF 50+', 'Wildlife is real, respect signs', 'Tipping not expected', 'Seasons are reversed from Korea'],
    mustPack: ['Passport + eVisitor', 'AUD cash', 'Type I adapter', 'Strong sunscreen', 'Hat and sunglasses', 'Layers'],
    weather: { spring: 'Sep-Nov, 15-25°C', summer: 'Dec-Feb, hot 25-35°C+', fall: 'Mar-May, cool', winter: 'Jun-Aug, cool 5-15°C' },
  },
  'Malaysia': {
    code: 'MY', currency: 'MYR', flag: '🇲🇾',
    capital: 'Kuala Lumpur', timezone: 'Asia/Kuala_Lumpur',
    lat: 3.1390, lng: 101.6869,
    plug: { type: 'Type G', voltage: '240V', note: 'Type G (UK) adapter required' },
    visa: { required: false, note: 'Visa-free for 90 days' },
    sim: 'Maxis, Celcom, Digi. Airport kiosks.',
    emergency: { all: '999' },
    payment: 'Cards widely accepted. Cash for markets. Grab is standard.',
    water: 'Tap water not drinkable.',
    tips: ['Multi-cultural — respect all customs', 'Cover shoulders and knees at mosques', 'Grab is reliable', 'Eat at hawker stalls'],
    mustPack: ['Passport', 'MYR cash', 'Type G adapter', 'Light clothes', 'Umbrella', 'Insect repellent'],
    weather: { spring: 'Hot and humid year-round', summer: 'Same', fall: 'Monsoon on east coast Nov-Feb', winter: 'Wet season in some regions' },
  },
  'Philippines': {
    code: 'PH', currency: 'PHP', flag: '🇵🇭',
    capital: 'Manila', timezone: 'Asia/Manila',
    lat: 14.5995, lng: 120.9842,
    plug: { type: 'Type A/B/C', voltage: '220V', note: 'Korean plugs often fit' },
    visa: { required: false, note: 'Visa-free for 30 days' },
    sim: 'Globe, Smart. Buy at airport.',
    emergency: { police: '117', fire: '160', ambulance: '911' },
    payment: 'Cash (PHP) mostly. Cards at hotels and malls. Grab works.',
    water: 'Tap water not drinkable.',
    tips: ['Tagalog and English are official', 'Beaches have entrance fees', 'Typhoons Jun-Nov', 'Bargain at markets'],
    mustPack: ['Passport', 'PHP/USD cash', 'Sunscreen', 'Swimwear', 'Insect repellent', 'Flashlight'],
    weather: { spring: 'Dry and hot Mar-May', summer: 'Wet Jun-Oct', fall: 'Still wet, typhoons', winter: 'Dry and cool Dec-Feb' },
  },
};

export function detectCountries(items = []) {
  const found = new Set();
  const keywords = {
    'Japan': ['일본', '도쿄', '오사카', '교토', '나고야', '삿포로', '후쿠오카', '나라', '신주쿠', '시부야', 'japan', 'tokyo', 'osaka', 'kyoto', 'nagoya', 'sapporo', 'fukuoka', 'nara', 'shinjuku', 'shibuya'],
    'Thailand': ['태국', '방콕', '치앙마이', '푸켓', '파타야', '코사무이', 'thailand', 'bangkok', 'chiang mai', 'phuket', 'pattaya', 'koh samui'],
    'France': ['프랑스', '파리', '니스', '리옹', '마르세유', 'france', 'paris', 'nice', 'lyon', 'marseille'],
    'Italy': ['이탈리아', '로마', '밀라노', '피렌체', '베네치아', '나폴리', 'italy', 'rome', 'milan', 'florence', 'venice', 'naples'],
    'Vietnam': ['베트남', '하노이', '호치민', '다낭', '호이안', '냐짱', 'vietnam', 'hanoi', 'ho chi minh', 'danang', 'hoi an', 'nha trang'],
    'Indonesia': ['인도네시아', '발리', '자카르타', '롬복', '코모도', 'indonesia', 'bali', 'jakarta', 'lombok', 'komodo'],
    'Spain': ['스페인', '바르셀로나', '마드리드', '세비야', '그라나다', 'spain', 'barcelona', 'madrid', 'seville', 'granada'],
    'USA': ['미국', '뉴욕', '로스앤젤레스', '라스베가스', '시카고', '하와이', '샌프란시스코', 'usa', 'new york', 'los angeles', 'las vegas', 'chicago', 'hawaii', 'san francisco'],
    'Singapore': ['싱가포르', 'singapore'],
    'Hong Kong': ['홍콩', 'hong kong', 'hongkong'],
    'UK': ['영국', '런던', '에든버러', '맨체스터', 'uk', 'london', 'edinburgh', 'manchester'],
    'Australia': ['호주', '시드니', '멜버른', '브리즈번', '퀸스타운', 'australia', 'sydney', 'melbourne', 'brisbane', 'queenstown'],
    'Malaysia': ['말레이시아', '쿠알라룸푸르', '페낭', '코타키나발루', 'malaysia', 'kuala lumpur', 'penang', 'kota kinabalu'],
    'Philippines': ['필리핀', '마닐라', '세부', '팔라완', '보라카이', 'philippines', 'manila', 'cebu', 'palawan', 'boracay'],
  };
  items.forEach(item => {
    const text = [(item.placeName || ''), (item.address || ''), (item.howToGet || '')].join(' ').toLowerCase();
    Object.entries(keywords).forEach(([country, kws]) => {
      if (kws.some(k => text.includes(k.toLowerCase()))) found.add(country);
    });
  });
  return [...found];
}
