export const COUNTRY_INFO = {
  '일본': {
    code: 'JP', currency: 'JPY', flag: '🇯🇵',
    capital: '도쿄', timezone: 'Asia/Tokyo',
    lat: 35.6762, lng: 139.6503,
    plug: { type: 'A형', voltage: '100V', note: '한국 돼지코 필요. 한국 제품 220V → 변압기 필수' },
    visa: { required: false, note: '무비자 90일 (관광)' },
    sim: '공항/편의점에서 구매 가능. 소프트뱅크·au·도코모 SIM 추천',
    emergency: { police: '110', fire: '119', ambulance: '119' },
    payment: '현금 위주 문화. 편의점·관광지 카드 가능. 엔화 환전 추천',
    water: '수돗물 음용 가능',
    tips: ['교통패스 (스이카·이코카) 미리 구매', '쓰레기통 없음 → 쓰레기 챙겨다니기', '식당 물은 무료', '신사 방문 시 조용히'],
    mustPack: ['여권 + 여분 사진', '엔화 현금', '돼지코 어댑터', '우산 (갑자기 비 많음)', '편한 운동화', '마스크'],
    weather: { spring: '벚꽃 시즌 3~4월, 15~20°C', summer: '7~8월 덥고 습함 30°C+', fall: '단풍 10~11월', winter: '눈 12~2월, 도쿄는 많지 않음' },
  },
  '태국': {
    code: 'TH', currency: 'THB', flag: '🇹🇭',
    capital: '방콕', timezone: 'Asia/Bangkok',
    lat: 13.7563, lng: 100.5018,
    plug: { type: 'A/B/C형', voltage: '220V', note: '한국 플러그 대부분 호환. 어댑터 불필요한 경우 많음' },
    visa: { required: false, note: '무비자 30일 (관광)' },
    sim: '공항에서 트루무브·AIS SIM 구매. 7일 무제한 약 2만원',
    emergency: { police: '191', fire: '199', ambulance: '1669' },
    payment: '현금(바트) 위주. 관광지 카드 가능. ATM 수수료 주의',
    water: '수돗물 음용 불가. 생수 구매 필수',
    tips: ['사원 방문 시 긴 옷 필수', '툭툭·택시 미터기 확인', '그랩 앱 유용', '더위 주의 → 물 많이 마시기'],
    mustPack: ['여권', '바트 현금', '선크림 (자외선 강함)', '반팔/반바지', '위장약', '모기 기피제', '긴 바지 (사원용)'],
    weather: { spring: '건기 끝 3~4월, 35°C+ 매우 더움', summer: '우기 5~10월, 소나기 잦음', fall: '우기 끝 10~11월', winter: '건기 11~2월, 최고 여행 시즌' },
  },
  '프랑스': {
    code: 'FR', currency: 'EUR', flag: '🇫🇷',
    capital: '파리', timezone: 'Europe/Paris',
    lat: 48.8566, lng: 2.3522,
    plug: { type: 'C/E형', voltage: '230V', note: '한국과 다름. C형 어댑터 필수' },
    visa: { required: false, note: '쉔겐 협정 무비자 90일' },
    sim: '공항/Orange·SFR 매장. eSIM 가능',
    emergency: { police: '17', fire: '18', ambulance: '15', eu통합: '112' },
    payment: '카드 사용 대부분 가능. 소액은 현금. 유로 소액 환전 권장',
    water: '수돗물 음용 가능',
    tips: ['소매치기 주의 (지하철·관광지)', '팁 문화 있음 (식당 5~10%)', '일요일 상점 많이 닫힘', '박물관 무료 첫째주 일요일'],
    mustPack: ['여권 + 복사본', '유로 현금', 'C형 어댑터', '긴 바지', '편한 걷기 신발', '작은 크로스백'],
    weather: { spring: '3~5월 쾌적 15~20°C', summer: '6~8월 28°C 여행 최적', fall: '9~11월 선선', winter: '12~2월 추움 5°C 내외' },
  },
  '이탈리아': {
    code: 'IT', currency: 'EUR', flag: '🇮🇹',
    capital: '로마', timezone: 'Europe/Rome',
    lat: 41.9028, lng: 12.4964,
    plug: { type: 'C/F/L형', voltage: '230V', note: 'C형 어댑터 필수' },
    visa: { required: false, note: '쉔겐 협정 무비자 90일' },
    sim: 'TIM·Vodafone·WindTre SIM 공항/가게에서 구매',
    emergency: { police: '113', fire: '115', ambulance: '118', eu통합: '112' },
    payment: '카드 사용 가능. 소액 현금 유용. 유로 환전 권장',
    water: '수돗물 음용 가능. 공공 분수대(나사로네) 무료 음용 가능',
    tips: ['콜로세움 예약 필수 (현장 구매 불가)', '식당 앉으면 코페르토(자리세) 부과', '소매치기 주의', '드레스코드 있는 성당 많음'],
    mustPack: ['여권', '유로 현금', 'C형 어댑터', '긴 바지 (성당용)', '편한 신발', '자외선 차단제'],
    weather: { spring: '3~5월 쾌적 15~22°C 최적', summer: '6~8월 30°C+ 덥고 혼잡', fall: '9~10월 선선하고 관광객 적음', winter: '11~2월 추움. 남부는 온화' },
  },
  '베트남': {
    code: 'VN', currency: 'VND', flag: '🇻🇳',
    capital: '하노이', timezone: 'Asia/Ho_Chi_Minh',
    lat: 21.0285, lng: 105.8542,
    plug: { type: 'A/C형', voltage: '220V', note: '대부분 호환. 일부 C형 어댑터 필요' },
    visa: { required: false, note: '무비자 45일 (2023년부터)' },
    sim: '공항에서 Viettel·Vinaphone SIM. 저렴하고 빠름',
    emergency: { police: '113', fire: '114', ambulance: '115' },
    payment: '현금(동) 위주. 대형 식당/호텔은 카드. 동 단위 크므로 계산 주의',
    water: '수돗물 음용 불가. 생수 필수',
    tips: ['오토바이 많아 횡단보도 주의', '그랩 앱 필수', '가격 흥정 문화', '쌀국수·반미 길거리 식사 추천'],
    mustPack: ['여권', '동 현금', '모기 기피제', '위장약', '선크림', '우산 (우기 시)'],
    weather: { spring: '하노이 봄 2~4월 쾌적', summer: '우기 5~10월', fall: '남부 건기 11~4월 최적', winter: '하노이 12~1월 서늘' },
  },
  '인도네시아': {
    code: 'ID', currency: 'IDR', flag: '🇮🇩',
    capital: '자카르타', timezone: 'Asia/Jakarta',
    lat: -8.4095, lng: 115.1889,
    plug: { type: 'C/F형', voltage: '230V', note: 'C형 어댑터 필요한 경우 있음' },
    visa: { required: false, note: '무비자 30일 (발리 등)' },
    sim: '공항에서 Telkomsel·XL SIM 구매',
    emergency: { police: '110', fire: '113', ambulance: '119' },
    payment: '현금(루피아) 위주. 루피아 단위 매우 크므로 계산 주의 (1만원 ≈ 10만 루피아)',
    water: '수돗물 음용 불가. 생수 필수',
    tips: ['발리는 힌두교 성지 → 사원 방문 시 사롱 착용', '라마단 기간 주의 (무슬림 지역)', '고젝·그랩 앱 사용'],
    mustPack: ['여권', '루피아 현금', '모기 기피제', '선크림', '사롱 (발리 사원용)', '위장약'],
    weather: { spring: '건기 5~9월 최적', summer: '건기 계속', fall: '우기 시작 10월', winter: '우기 11~4월. 비 자주 옴' },
  },
  '스페인': {
    code: 'ES', currency: 'EUR', flag: '🇪🇸',
    capital: '마드리드', timezone: 'Europe/Madrid',
    lat: 40.4168, lng: -3.7038,
    plug: { type: 'C/F형', voltage: '230V', note: 'C형 어댑터 필수' },
    visa: { required: false, note: '쉔겐 협정 무비자 90일' },
    sim: '공항/Movistar·Vodafone 매장',
    emergency: { police: '091', fire: '080', ambulance: '061', eu통합: '112' },
    payment: '카드 대부분 사용 가능. 소액 현금 유용',
    water: '수돗물 음용 가능',
    tips: ['낮잠(시에스타) 시간 14~17시 상점 닫힘', '저녁 식사는 21시 이후', '소매치기 주의 (바르셀로나 람블라스)', '플라멩코 공연 예약 권장'],
    mustPack: ['여권', '유로 현금', 'C형 어댑터', '편한 걷기 신발', '선크림', '부채 (여름)'],
    weather: { spring: '3~5월 쾌적 18~23°C', summer: '6~8월 35°C+ 매우 더움', fall: '9~11월 선선하고 좋음', winter: '12~2월 쌀쌀. 남부는 온화' },
  },
  '미국': {
    code: 'US', currency: 'USD', flag: '🇺🇸',
    capital: '워싱턴 D.C.', timezone: 'America/New_York',
    lat: 40.7128, lng: -74.0060,
    plug: { type: 'A형', voltage: '120V', note: '한국과 같은 A형이나 전압 다름. 요즘 기기 대부분 호환 (어댑터 확인)' },
    visa: { required: true, note: 'ESTA 사전 신청 필수 (72시간 전, 약 $21). esta.cbp.dhs.gov' },
    sim: '공항/T-Mobile·AT&T SIM. eSIM 추천',
    emergency: { police: '911', fire: '911', ambulance: '911' },
    payment: '카드 거의 모든 곳 사용. 팁 문화 필수 (식당 15~20%)',
    water: '수돗물 음용 가능 (도시별 다름)',
    tips: ['팁 문화 필수 (식당·택시·호텔)', 'ESTA 사전 신청', '주마다 세금 다름', '약국 OTC 의약품 다양'],
    mustPack: ['여권 + ESTA 신청확인서', '달러 현금 (팁용)', '국제운전면허 (렌터카 시)', '상비약'],
    weather: { spring: '지역별 다름. 뉴욕 3~5월 쾌적', summer: '6~8월 더움. LA는 쾌적', fall: '9~11월 단풍 아름다움', winter: '북부 눈. 남부/서부 온화' },
  },
  '싱가포르': {
    code: 'SG', currency: 'SGD', flag: '🇸🇬',
    capital: '싱가포르', timezone: 'Asia/Singapore',
    lat: 1.3521, lng: 103.8198,
    plug: { type: 'G형', voltage: '230V', note: '영국식 3핀. G형 어댑터 필수' },
    visa: { required: false, note: '무비자 30일' },
    sim: '공항/Singtel·StarHub SIM. 저렴하고 빠름',
    emergency: { police: '999', fire: '995', ambulance: '995' },
    payment: '카드·현금 모두 편리. PayNow 등 간편결제 발달',
    water: '수돗물 음용 가능 (아시아 최고 수준)',
    tips: ['껌 소지·판매 금지', '공공장소 음식물 제한', '에어컨 실내 매우 춥게 함 → 겉옷 준비', 'MRT 가장 편리'],
    mustPack: ['여권', '싱가포르달러 소액', 'G형 어댑터', '얇은 긴 옷 (실내 에어컨)', '선크림'],
    weather: { spring: '연중 30°C 내외. 열대 기후', summer: '6~8월 건기', fall: '9~11월 우기 시작', winter: '12~1월 북동계절풍. 비 많음' },
  },
  '홍콩': {
    code: 'HK', currency: 'HKD', flag: '🇭🇰',
    capital: '홍콩', timezone: 'Asia/Hong_Kong',
    lat: 22.3193, lng: 114.1694,
    plug: { type: 'G형', voltage: '220V', note: '영국식 3핀. G형 어댑터 필수' },
    visa: { required: false, note: '무비자 90일' },
    sim: '공항에서 3HK·CMHK SIM. 저렴하고 빠름',
    emergency: { police: '999', fire: '999', ambulance: '999' },
    payment: '카드·현금 모두 가능. 옥토퍼스 카드 편리',
    water: '수돗물 음용 가능하나 생수 권장',
    tips: ['옥토퍼스 카드 (교통+결제)', 'MTR 지하철 가장 편리', '딤섬 아침 식사 추천', '빅토리아 피크 야경 필수'],
    mustPack: ['여권', '홍콩달러 소액', 'G형 어댑터', '우산 (비 많음)', '얇은 겉옷'],
    weather: { spring: '3~4월 흐리고 습함', summer: '5~9월 덥고 태풍 주의', fall: '10~11월 최고 시즌 쾌적', winter: '12~2월 서늘 15°C 내외' },
  },
  '영국': {
    code: 'GB', currency: 'GBP', flag: '🇬🇧',
    capital: '런던', timezone: 'Europe/London',
    lat: 51.5074, lng: -0.1278,
    plug: { type: 'G형', voltage: '230V', note: 'G형 어댑터 필수 (영국 전용 3핀)' },
    visa: { required: false, note: '무비자 6개월 (관광). ETA 사전 신청 필요 (£10)' },
    sim: '공항/Tesco·EE·O2 SIM',
    emergency: { police: '999', fire: '999', ambulance: '999', eu: '112' },
    payment: '카드 거의 모든 곳 사용. 파운드 소액 현금 유용',
    water: '수돗물 음용 가능',
    tips: ['왼쪽 통행 (차량·에스컬레이터)', '티타임 문화', '박물관 대부분 무료', '지하철(튜브) 오이스터 카드 이용'],
    mustPack: ['여권 + ETA', '파운드 소액', 'G형 어댑터', '우산 (갑자기 비)', '따뜻한 겉옷'],
    weather: { spring: '3~5월 쌀쌀 12°C. 비 잦음', summer: '6~8월 20~25°C 여행 최적', fall: '9~10월 선선하고 쾌적', winter: '11~2월 5°C 내외. 흐리고 비' },
  },
  '호주': {
    code: 'AU', currency: 'AUD', flag: '🇦🇺',
    capital: '캔버라', timezone: 'Australia/Sydney',
    lat: -33.8688, lng: 151.2093,
    plug: { type: 'I형', voltage: '230V', note: 'I형 어댑터 필수 (독특한 3핀)' },
    visa: { required: true, note: 'ETA 사전 신청 필수 (AUD$20). 앱으로 신청' },
    sim: '공항/Telstra·Optus·Vodafone SIM',
    emergency: { police: '000', fire: '000', ambulance: '000' },
    payment: '카드 거의 모든 곳 사용. 팁 문화 없음',
    water: '수돗물 음용 가능',
    tips: ['자외선 매우 강함 → SPF50+ 필수', '야생동물 주의 (캥거루 도로 출몰)', '팁 문화 없음', '물가 비쌈'],
    mustPack: ['여권 + ETA', '호주달러 소액', 'I형 어댑터', 'SPF50+ 선크림', '선글라스', '모자'],
    weather: { spring: '남반구 반대. 9~11월 봄. 쾌적 20°C', summer: '12~2월 한여름 35°C+', fall: '3~5월 가을. 여행 좋음', winter: '6~8월 겨울. 남부 춥고 북부 건기' },
  },
  '말레이시아': {
    code: 'MY', currency: 'MYR', flag: '🇲🇾',
    capital: '쿠알라룸푸르', timezone: 'Asia/Kuala_Lumpur',
    lat: 3.1390, lng: 101.6869,
    plug: { type: 'G형', voltage: '240V', note: 'G형 어댑터 필요. 일부 숙소 멀티어댑터 제공' },
    visa: { required: false, note: '무비자 90일' },
    sim: '공항/Maxis·Celcom SIM',
    emergency: { police: '999', fire: '994', ambulance: '999' },
    payment: '카드·현금 모두 가능. 링깃 환전 권장',
    water: '수돗물 음용 불가. 생수 필수',
    tips: ['무슬림 국가 → 라마단 기간 주의', '그랩 앱 필수', 'KL 교통 KLCC·KLMRT 편리', '할랄 음식 많음'],
    mustPack: ['여권', '링깃 현금', 'G형 어댑터', '선크림', '모기 기피제', '얇은 긴 옷 (사원용)'],
    weather: { spring: '연중 28~33°C 열대', summer: '우기 지역별 다름', fall: '동해안 우기 10~2월', winter: '서해안은 연중 맑음' },
  },
  '필리핀': {
    code: 'PH', currency: 'PHP', flag: '🇵🇭',
    capital: '마닐라', timezone: 'Asia/Manila',
    lat: 14.5995, lng: 120.9842,
    plug: { type: 'A/B형', voltage: '220V', note: '한국 플러그 대부분 호환' },
    visa: { required: false, note: '무비자 30일 (도착 비자 연장 가능)' },
    sim: '공항/Smart·Globe SIM',
    emergency: { police: '911', fire: '911', ambulance: '911' },
    payment: '현금(페소) 위주. 관광지 카드 가능',
    water: '수돗물 음용 불가. 생수 필수',
    tips: ['지프니·트라이시클 현지 교통', '태풍 시즌 7~9월 주의', '도서 지역 이동 시 보트 이용', '세부·팔라완 스노클링 유명'],
    mustPack: ['여권', '페소 현금', '선크림', '래시가드', '모기 기피제', '방수백'],
    weather: { spring: '건기 3~5월. 덥고 맑음', summer: '우기 6~10월. 태풍 주의', fall: '우기 끝. 태풍 잦음', winter: '건기 11~2월. 여행 최적' },
  },
};

// 나라 감지 (장소명/국가명 기반)
export function detectCountries(items = []) {
  const found = new Set();
  const keywords = {
    '일본': ['일본', '도쿄', '오사카', '교토', '나고야', '삿포로', '후쿠오카', '나라', '도쿄', '신주쿠', '시부야', 'japan', 'tokyo', 'osaka'],
    '태국': ['태국', '방콕', '치앙마이', '푸켓', '파타야', '코사무이', 'thailand', 'bangkok'],
    '프랑스': ['프랑스', '파리', '니스', '리옹', '마르세유', 'france', 'paris'],
    '이탈리아': ['이탈리아', '로마', '밀라노', '피렌체', '베네치아', '나폴리', 'italy', 'rome'],
    '베트남': ['베트남', '하노이', '호치민', '다낭', '호이안', '냐짱', 'vietnam'],
    '인도네시아': ['인도네시아', '발리', '자카르타', '롬복', '코모도', 'indonesia', 'bali'],
    '스페인': ['스페인', '바르셀로나', '마드리드', '세비야', '그라나다', 'spain', 'barcelona'],
    '미국': ['미국', '뉴욕', '로스앤젤레스', '라스베가스', '시카고', '하와이', '샌프란시스코', 'usa', 'new york'],
    '싱가포르': ['싱가포르', 'singapore'],
    '홍콩': ['홍콩', 'hong kong', 'hongkong'],
    '영국': ['영국', '런던', '에든버러', '맨체스터', 'uk', 'london'],
    '호주': ['호주', '시드니', '멜버른', '브리즈번', '퀸스타운', 'australia', 'sydney'],
    '말레이시아': ['말레이시아', '쿠알라룸푸르', '페낭', '코타키나발루', 'malaysia'],
    '필리핀': ['필리핀', '마닐라', '세부', '팔라완', '보라카이', 'philippines'],
  };
  items.forEach(item => {
    const text = [(item.placeName || ''), (item.address || ''), (item.howToGet || '')].join(' ').toLowerCase();
    Object.entries(keywords).forEach(([country, kws]) => {
      if (kws.some(k => text.includes(k.toLowerCase()))) found.add(country);
    });
  });
  return [...found];
}
